db:
  username: postgres
  password: root
  driver: PostgresDriver
  url: postgres:5432
  hosts: localhost,127.0.0.1
  properties:
    first: 1
    last: 2
    key: value
  pool:
    size: 10
    timeout: 20
  pools:
    - size: 10
      timeout: 20
    - size: 10
      timeout: 20
    - size: 10
      timeout: 20

logging:
  level:
    root: WARN
    by.danilko.spring.database.repository.pool.ConnectionPool: INFO
  file:
    name: by.danilko
    path: /